name: main

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      - name: Test
        run: pnpm test
